# Generated by Django 5.2.4 on 2025-07-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_app', '0002_alter_admin_password_alter_admin_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='sinopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
