# Generated by Django 5.2.4 on 2025-07-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_app', '0003_film_sinopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='imdb_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
